# Generated by Django 4.0.3 on 2022-04-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
