# Generated by Django 4.0.3 on 2022-05-10 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_details', models.CharField(max_length=300)),
                ('product_expiryDate', models.CharField(default='2022-05-30', max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_location', models.CharField(max_length=100)),
                ('product_visibility', models.BooleanField()),
                ('product_sold', models.BooleanField()),
                ('product_checkExpired', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_image', models.ImageField(default='product_images/default_img.png', upload_to='product_images')),
                ('product_category', models.CharField(default='Others', max_length=100)),
                ('product_info', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='homePage.productinfo', verbose_name='ProductID')),
            ],
        ),
    ]
